# Generated by Django 3.1.7 on 2021-04-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210419_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
    ]
