# Generated by Django 3.1.7 on 2021-04-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210419_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsModel',
        ),
    ]
