# Generated by Django 3.1.7 on 2021-04-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_newsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='file_1',
            field=models.FileField(upload_to=''),
        ),
    ]
