# Generated by Django 3.1.7 on 2021-04-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=300, verbose_name='Метод классификации')),
                ('model', models.CharField(max_length=300, verbose_name='Модель для классификации')),
                ('title', models.CharField(max_length=300, verbose_name='Название проверки')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Проверка новости',
                'verbose_name_plural': 'Проверки новостей',
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
