# Generated by Django 3.1.7 on 2021-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210401_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='method',
            field=models.BooleanField(default=False, verbose_name='Текст?'),
        ),
    ]
