# Generated by Django 3.1.7 on 2021-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210401_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='method',
            field=models.CharField(choices=[('0', 'Проверка текста'), ('1', 'Проверка ссылки')], default='0', max_length=50, verbose_name='Текст или ссылка?'),
        ),
    ]
