# Generated by Django 3.1.7 on 2021-04-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_check_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='verdict',
            field=models.CharField(default='Не проверено', max_length=50, verbose_name='Вердикт'),
        ),
    ]
