# Generated by Django 3.1.7 on 2021-04-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_check_verdict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
