# Generated by Django 3.1.7 on 2021-04-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
    ]
