# Generated by Django 3.1.7 on 2021-04-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_newsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='file_1',
            field=models.CharField(max_length=300, verbose_name='Файл 1'),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='file_2',
            field=models.CharField(max_length=300, verbose_name='Файл 2'),
        ),
    ]
