# Generated by Django 3.1.7 on 2021-04-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210421_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='new_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.newsmodel'),
        ),
    ]
