# Generated by Django 3.1.7 on 2021-04-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_check_new_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='new_model',
        ),
        migrations.AlterField(
            model_name='check',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.newsmodel'),
        ),
    ]
