# Generated by Django 3.1.7 on 2021-05-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
