# Generated by Django 3.1.7 on 2021-05-06 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210506_1906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
