# Generated by Django 3.1.7 on 2021-05-18 20:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_askrightsmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check',
            new_name='CheckModel',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='file_1',
            new_name='file_model',
        ),
        migrations.RenameField(
            model_name='newsmodel',
            old_name='file_2',
            new_name='file_vector',
        ),
    ]
