# Generated by Django 3.1.7 on 2021-05-24 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210524_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='file_vector',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['pkl'])]),
        ),
    ]
